[package]
name = "daemon"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/nyanzebra/daemon"

[dependencies]
libc = "0.2"
log = "0.4"
schemars = "1.2.2"
serde = { version = "1", features = ["derive"] }
thiserror = "2"

[dev-dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
serde_json = "1.0.151"
toml = "0.8"
